---
name: Validate
on:
  workflow_call:

env:
  GO_VERSION: 'stable'
  GOLANGCI_VERSION: 'latest'

jobs:
  Lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          only-new-issues: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.GOLANGCI_VERSION }}
          args: '-c .golangci.yaml'
  Validate:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: ⚙️ Run test suite
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_SUITE_PAT }}
          TEST_SUITE_REPOSITORY: ${{ secrets.TEST_SUITE_REPOSITORY }}
      - run: go tool cover -func=coverage.txt
